name    'erwbgy-autohome'
version '0.1.0'
source 'https://github.com/erwbgy/puppet-autohome.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Automount home directories'
description 'Automount home directories'
project_page 'git.com:erwbgy/puppet-autohome.git'
